name: TwerkFarm
version: ${project.version}
main: com.blackbeltpanda.twerkfarm.TwerkFarm
api-version: 1.17
authors: [ BlackBeltPanda ]
description: Twerk to farm!
website: https://github.com/BlackBeltPanda/TwerkFarm
commands:
  twerkfarm:
    description: TwerkFarm command
    aliases:
      - twerk
      - tw
      - tf
    permission: twerkfarm.command
    usage: /<command> [reload|version]
permissions:
  twerkfarm.twerk:
    description: Allows a player to use the twerk feature
    default: true
  twerkfarm.twerk.*:
    description: Allows a player to twerk to grow all nearby whitelisted blocks
    default: false
    children:
      twerkfarm.twerk: true
  twerkfarm.command:
    description: Allows access to the /twerkfarm command
    default: op
  twerkfarm.*:
    description: Allows access to all TwerkFarm permissions
    default: op
    children:
      twerkfarm.command: true
      twerkfarm.twerk.*: true